MCTSCompetitor 1 wins the tournament!
ELO 1380.4352321771335
============================================
Ejecución iniciada el: 2025-05-17 13:51:56
--------------------------------------------
Traceback (most recent call last):
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 46, in <module>
    main(args)
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 25, in main
    championship.run()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 63, in run
    self._build_teams()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 70, in _build_teams
    cm.team = build_team(cm.competitor.team_build_policy.decision(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/net/client.py", line 49, in decision
    return self.conn.recv()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError

Log generado el: 2025-05-17 13:51:57
Duración total: 0.10 minutos

============================================
Ejecución iniciada el: 2025-05-17 13:54:03
--------------------------------------------
LLM_MCTSCompetitor 1 wins the tournament!
ELO 1277.6713322066962

Log generado el: 2025-05-17 13:54:20
Duración total: 0.43 minutos

============================================
Ejecución iniciada el: 2025-05-17 16:46:25
--------------------------------------------
Traceback (most recent call last):
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 46, in <module>
    main(args)
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 25, in main
    championship.run()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 63, in run
    self._build_teams()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 70, in _build_teams
    cm.team = build_team(cm.competitor.team_build_policy.decision(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/net/client.py", line 49, in decision
    return self.conn.recv()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError

Log generado el: 2025-05-17 16:46:25
Duración total: 0.08 minutos

============================================
Ejecución iniciada el: 2025-05-17 16:47:00
--------------------------------------------
Traceback (most recent call last):
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 46, in <module>
    main(args)
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 25, in main
    championship.run()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 63, in run
    self._build_teams()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 70, in _build_teams
    cm.team = build_team(cm.competitor.team_build_policy.decision(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/net/client.py", line 49, in decision
    return self.conn.recv()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError

Log generado el: 2025-05-17 16:47:05
Duración total: 0.17 minutos

============================================
Ejecución iniciada el: 2025-05-17 16:54:40
--------------------------------------------
LLM_MCTSCompetitor 1 wins the tournament!
ELO 1315.1808054472153

Log generado el: 2025-05-17 16:54:54
Duración total: 0.37 minutos

============================================
Ejecución iniciada el: 2025-05-17 17:15:37
--------------------------------------------
Example 0 wins the tournament!
ELO 1279.445355520038

Log generado el: 2025-05-17 17:15:50
Duración total: 0.37 minutos

