============================================
Ejecución iniciada el: 2025-05-19 19:12:44
Competidores: 20 (LLM en ID=1)
--------------------------------------------
Example 0 wins the tournament!
ELO 1258.2236855884348

Finalizado : 2025-05-19 19:18:04
Duración   : 5.42 minutos

============================================
Ejecución iniciada el: 2025-05-19 19:20:30
Competidores: 20 (LLM en ID=1)
--------------------------------------------
LLM_Competitor 1 wins the tournament!
ELO 1374.8813390917135

Finalizado : 2025-05-19 19:31:00
Duración   : 10.58 minutos

============================================
Ejecución iniciada el: 2025-05-19 19:42:46
Competidores: 20 (LLM en ID=1)
--------------------------------------------
Example 6 wins the tournament!
ELO 1293.214628502482

Finalizado : 2025-05-19 19:51:10
Duración   : 8.48 minutos

============================================
Ejecución iniciada el: 2025-05-19 20:38:17
Competidores: 20 (LLM en ID=1)
--------------------------------------------
LLM_Competitor 1 wins the tournament!
ELO 1380.4352321771335

Finalizado : 2025-05-19 20:46:19
Duración   : 8.12 minutos

============================================
Ejecución iniciada el: 2025-05-19 21:23:34
Competidores: 2 (LLM en ID=1)
--------------------------------------------
Traceback (most recent call last):
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 46, in <module>
    main(args)
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 25, in main
    championship.run()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 63, in run
    self._build_teams()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 70, in _build_teams
    cm.team = build_team(cm.competitor.team_build_policy.decision(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/net/client.py", line 49, in decision
    return self.conn.recv()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError
============================================
Ejecución iniciada el: 2025-05-19 21:24:06
Competidores: 2 (LLM en ID=1)
--------------------------------------------
LLM_Competitor 1 wins the tournament!
ELO 1251.9587497839718

Finalizado : 2025-05-19 21:24:23
Duración   : 0.37 minutos

============================================
Ejecución iniciada el: 2025-05-19 21:26:18
Competidores: 2 (LLM en ID=1)
--------------------------------------------
Traceback (most recent call last):
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 46, in <module>
    main(args)
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 25, in main
    championship.run()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 63, in run
    self._build_teams()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 70, in _build_teams
    cm.team = build_team(cm.competitor.team_build_policy.decision(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/net/client.py", line 49, in decision
    return self.conn.recv()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError
============================================
Ejecución iniciada el: 2025-05-19 21:26:43
Competidores: 2 (LLM en ID=1)
--------------------------------------------
LLM_Competitor 1 wins the tournament!
ELO 1210.0440203589746

Finalizado : 2025-05-19 21:27:05
Duración   : 0.45 minutos

============================================
Ejecución iniciada el: 2025-05-19 21:38:50
Competidores: 2 (LLM en ID=1)
--------------------------------------------
Traceback (most recent call last):
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 46, in <module>
    main(args)
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 25, in main
    championship.run()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 63, in run
    self._build_teams()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 70, in _build_teams
    cm.team = build_team(cm.competitor.team_build_policy.decision(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/net/client.py", line 49, in decision
    return self.conn.recv()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError
============================================
Ejecución iniciada el: 2025-05-19 21:39:14
Competidores: 2 (LLM en ID=1)
--------------------------------------------
Traceback (most recent call last):
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 46, in <module>
    main(args)
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 25, in main
    championship.run()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 63, in run
    self._build_teams()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 70, in _build_teams
    cm.team = build_team(cm.competitor.team_build_policy.decision(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/net/client.py", line 49, in decision
    return self.conn.recv()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError
============================================
Ejecución iniciada el: 2025-05-19 21:39:46
Competidores: 2 (LLM en ID=1)
--------------------------------------------
Traceback (most recent call last):
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 46, in <module>
    main(args)
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 25, in main
    championship.run()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 63, in run
    self._build_teams()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 70, in _build_teams
    cm.team = build_team(cm.competitor.team_build_policy.decision(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/net/client.py", line 49, in decision
    return self.conn.recv()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError
============================================
Ejecución iniciada el: 2025-05-19 21:44:56
Competidores: 2 (LLM en ID=1)
--------------------------------------------
Traceback (most recent call last):
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 46, in <module>
    main(args)
  File "/home/geo/pokemon-vgc-ai/pokemon-vgc-engine/organization/run_championship_track.py", line 25, in main
    championship.run()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 63, in run
    self._build_teams()
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/competition/ecosystem.py", line 70, in _build_teams
    cm.team = build_team(cm.competitor.team_build_policy.decision(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/geo/pokemon-vgc-ai/venv/lib/python3.12/site-packages/vgc2/net/client.py", line 49, in decision
    return self.conn.recv()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError
============================================
Ejecución iniciada el: 2025-05-19 21:46:33
Competidores: 2 (LLM en ID=1)
--------------------------------------------
LLM_Competitor 1 wins the tournament!
ELO 1368.9649501865938

Finalizado : 2025-05-19 21:46:55
Duración   : 0.45 minutos

